from app.db.base_class import Base
from app.models.academy import Academy
from app.models.honor import Honor
from app.models.grades import Grades
from app.models.sportstest import Sportstest
from app.models.classes import Classes
from app.models.student import Student
from app.models.user import User
from app.models.average_grades import AverageGrade
from app.models.checktable import CheckTable
from app.models.moral import Moral
from app.models.physical_mind import PhysicalMind
