"""5_21_update

Revision ID: f62633480c40
Revises: 
Create Date: 2021-05-21 01:50:38.972125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62633480c40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academy_name', sa.String(length=30), nullable=False),
    sa.Column('discipline_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academy_academy_name'), 'academy', ['academy_name'], unique=False)
    op.create_index(op.f('ix_academy_discipline_name'), 'academy', ['discipline_name'], unique=False)
    op.create_index(op.f('ix_academy_id'), 'academy', ['id'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('必修课', '选修课'), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False, comment='学时'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_class_name'), 'classes', ['class_name'], unique=False)
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False, comment='老师的工号'),
    sa.Column('full_name', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('prof', sa.String(length=20), nullable=True, comment='老师的职称'),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='False为老师，True为超级管理员'),
    sa.Column('gender', sa.Enum('男', '女'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=False)
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False, comment='学号'),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.Enum('男', '女'), nullable=True),
    sa.Column('political_status', sa.Enum('群众', '团员', '积极分子', '预备党员', '党员'), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id_second', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(length=150), nullable=False),
    sa.Column('admission_time', sa.Date(), nullable=True),
    sa.Column('graduate_time', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['academy.id'], ),
    sa.ForeignKeyConstraint(['discipline_id_second'], ['academy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_id'), 'student', ['id'], unique=True)
    op.create_index(op.f('ix_student_name'), 'student', ['name'], unique=False)
    op.create_index(op.f('ix_student_phone_number'), 'student', ['phone_number'], unique=False)
    op.create_table('averagegrade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('grades', sa.Float(), nullable=True, comment='平均学分绩'),
    sa.Column('grade', sa.Enum('大一', '大二', '大三', '大四', '大五', '大六'), nullable=False, comment='年级'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id', 'student_id')
    )
    op.create_index(op.f('ix_averagegrade_grade'), 'averagegrade', ['grade'], unique=False)
    op.create_table('checktable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Enum('大一', '大二', '大三', '大四'), nullable=False, comment='年级'),
    sa.Column('honor', sa.Boolean(), nullable=True, comment='荣誉'),
    sa.Column('sports_test', sa.Boolean(), nullable=True, comment='体测得分'),
    sa.Column('physical_mind', sa.Boolean(), nullable=True, comment='体育和美术'),
    sa.Column('moral', sa.Boolean(), nullable=True, comment='品德'),
    sa.Column('average_grades', sa.Boolean(), nullable=True, comment='学分绩'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id', 'student_id')
    )
    op.create_index(op.f('ix_checktable_grade'), 'checktable', ['grade'], unique=False)
    op.create_index(op.f('ix_checktable_student_id'), 'checktable', ['student_id'], unique=False)
    op.create_table('grades',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('class_id', 'student_id')
    )
    op.create_index(op.f('ix_grades_class_id'), 'grades', ['class_id'], unique=False)
    op.create_index(op.f('ix_grades_student_id'), 'grades', ['student_id'], unique=False)
    op.create_table('honor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('奖学金', '竞赛', '荣誉称号'), nullable=False),
    sa.Column('describe', sa.String(length=100), nullable=False),
    sa.Column('classes', sa.Enum('思想品德', '学业', '文体'), nullable=True),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.Column('is_check', sa.Enum('通过', '未通过', '待审核'), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id', 'student_id')
    )
    op.create_index(op.f('ix_honor_describe'), 'honor', ['describe'], unique=False)
    op.create_index(op.f('ix_honor_id'), 'honor', ['id'], unique=False)
    op.create_index(op.f('ix_honor_student_id'), 'honor', ['student_id'], unique=False)
    op.create_index(op.f('ix_honor_type'), 'honor', ['type'], unique=False)
    op.create_table('moral',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('political_status', sa.Integer(), nullable=True),
    sa.Column('keep_law', sa.Integer(), nullable=True),
    sa.Column('collective_honor', sa.Integer(), nullable=True),
    sa.Column('self_cultivation', sa.Integer(), nullable=True, comment='基础文明修养'),
    sa.Column('dormitory_honor', sa.Integer(), nullable=True, comment='寝室文明'),
    sa.Column('social_practice', sa.Integer(), nullable=True, comment='社会实践'),
    sa.Column('extra_points', sa.Integer(), nullable=True, comment='额外加分'),
    sa.Column('deduction_points', sa.Integer(), nullable=True, comment='扣分项'),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id', 'student_id')
    )
    op.create_index(op.f('ix_moral_id'), 'moral', ['id'], unique=False)
    op.create_index(op.f('ix_moral_student_id'), 'moral', ['student_id'], unique=False)
    op.create_table('physicalmind',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.Float(), nullable=True, comment='自评加分'),
    sa.Column('ext_points', sa.Float(), nullable=True, comment='额外加分，最高30'),
    sa.Column('deduction_points', sa.Float(), nullable=True, comment='扣分项'),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id', 'student_id')
    )
    op.create_index(op.f('ix_physicalmind_id'), 'physicalmind', ['id'], unique=False)
    op.create_index(op.f('ix_physicalmind_student_id'), 'physicalmind', ['student_id'], unique=False)
    op.create_table('sportstest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('grades', sa.Float(), nullable=False, comment='得分'),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id', 'student_id')
    )
    op.create_index(op.f('ix_sportstest_id'), 'sportstest', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sportstest_id'), table_name='sportstest')
    op.drop_table('sportstest')
    op.drop_index(op.f('ix_physicalmind_student_id'), table_name='physicalmind')
    op.drop_index(op.f('ix_physicalmind_id'), table_name='physicalmind')
    op.drop_table('physicalmind')
    op.drop_index(op.f('ix_moral_student_id'), table_name='moral')
    op.drop_index(op.f('ix_moral_id'), table_name='moral')
    op.drop_table('moral')
    op.drop_index(op.f('ix_honor_type'), table_name='honor')
    op.drop_index(op.f('ix_honor_student_id'), table_name='honor')
    op.drop_index(op.f('ix_honor_id'), table_name='honor')
    op.drop_index(op.f('ix_honor_describe'), table_name='honor')
    op.drop_table('honor')
    op.drop_index(op.f('ix_grades_student_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_class_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_checktable_student_id'), table_name='checktable')
    op.drop_index(op.f('ix_checktable_grade'), table_name='checktable')
    op.drop_table('checktable')
    op.drop_index(op.f('ix_averagegrade_grade'), table_name='averagegrade')
    op.drop_table('averagegrade')
    op.drop_index(op.f('ix_student_phone_number'), table_name='student')
    op.drop_index(op.f('ix_student_name'), table_name='student')
    op.drop_index(op.f('ix_student_id'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_class_name'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_academy_id'), table_name='academy')
    op.drop_index(op.f('ix_academy_discipline_name'), table_name='academy')
    op.drop_index(op.f('ix_academy_academy_name'), table_name='academy')
    op.drop_table('academy')
    # ### end Alembic commands ###
