from .user import User
from .moral import Moral
from .physical_mind import PhysicalMind
from .academy import Academy
from .average_grades import AverageGrade
from .student import Student
from .classes import Classes
from .checktable import CheckTable
from .sportstest import Sportstest
from .honor import Honor
from .grades import Grades
